#page title
page_title                                : "二次会サーチ - 今、営業中のお店を探すアプリ"                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
# ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
# ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.codewithandrea.flutter_tips_and_tricks&hl=ja                                           # Enter Google Play Store URL.
# presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :  assets/icon_ios.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : 二次会サーチ                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 今、営業中のお店を探すアプリ                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : |-
  「二次会いこ！」「近くに開いてる店あるかな？」 
  本アプリは、今、営業中の近くの飲食店を表示するアプリです。 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : funappy_app                              
your_link                                 : https://funappy2.github.io                     
your_city                                 : Tokyo                             
email_address                             : funapp.app@gmail.com
# facebook_username                         :                                           
# instagram_username                        : ebaehr
# twitter_username                          : ebaehr
# github_username                           : emilbaehr
# youtube_username                          :
# mastodon_link                             : https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : 近くの営業中の飲食店が一目でわかる
    description                           : 現在位置を利用し、HotPepperに掲載されている、近くで営業中の飲食店を一覧表示します。まだ開いているお店が一目でわかるので、二次会のお店探しに便利です。
    fontawesome_icon_name                 : clock
    
  - title                                 : 残りの営業時間や現在地からの距離も表示
    description                           : あと何時間営業しているのか、現在地からの距離など、お店選びに役立つ情報を掲載しています。
    fontawesome_icon_name                 : circle-info

  - title                                 : おすすめのメニューや予算も簡単にチェック
    description                           : 店舗詳細画面では、ジャンル、イチ押し商品、カード使用可否などが確認できます。
    fontawesome_icon_name                 : utensils

  - title                                 : お店の場所をマップで確認
    description                           : お店の情報とともに、マップを表示できるので、迷うことなくお店に行けます。
    fontawesome_icon_name                 : map-location-dot




# Theme Settings
topbar_color                              : "#d0111b"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
# cover_overlay_color                       : "#363b3d"
# cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
